//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.Script.Serialization;
using System.Web.Security;
using System.Web.Services;
using SapiensProject.Controllers;

namespace SapiensProject.Views.Account
{


    public partial class Login
    {



        [WebMethod]
        public static string ValidaLogin(string txtUserName, string txtPassword, string player_id)
        {
            //string txtUserName = "8-1141-2313";
            //string txtPassword = "8-1141-2313";
            double time = 20000;
            txtUserName = txtUserName.Trim();
            txtPassword = txtPassword.Trim();
            player_id = player_id.Trim();
            if ((txtUserName == "") || (txtPassword == "")) return "{}";

            AccountController account = new AccountController();
            if (account.esUsuarioValido(txtUserName, txtPassword, player_id))
            {
                JavaScriptSerializer jss = new JavaScriptSerializer();
                string userData = jss.Serialize(account.currentUser);
                FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, account.currentUser.NombreUsuario, DateTime.Now, DateTime.Now.AddMinutes(time), true, userData, FormsAuthentication.FormsCookiePath);
                string encTicket = FormsAuthentication.Encrypt(ticket);
                HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
                cookie.Expires = DateTime.Now.AddMinutes(480);
                HttpContext.Current.Response.AppendHeader("Access-Control-Allow-Origin", "*");
                return cookie.Value;
            }
            return "{}";

        }
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
